# Generated by Django 3.1.6 on 2021-02-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210203_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='price',
        ),
    ]
