# Generated by Django 3.1.6 on 2021-02-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210203_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
