# Generated by Django 3.1.6 on 2021-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210203_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
