# Generated by Django 3.1.6 on 2021-02-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='test',
        ),
    ]
